In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('E-commerce.csv')
df.describe()

       Customer ID        Age  Annual Income  Time on Site
count    50.000000  50.000000      50.000000     50.000000
mean   1004.880000  39.960000   65780.000000    232.597000
std       3.623281  11.067437   17059.667198    109.669736
min    1001.000000  24.000000   40000.000000     32.500000
25%    1002.000000  30.250000   50500.000000    124.100000
50%    1004.000000  37.000000   65000.000000    243.450000
75%    1007.750000  48.000000   80000.000000    300.000000
max    1013.000000  65.000000  100000.000000    486.300000

In [2]:
df.head()

,Customer ID,Age,Gender,Location,Annual Income,Purchase History,Browsing History,Product Reviews,Time on Site
0,1001,25,Female,City D,45000,"[{""Date"": ""2022-03-05"", ""Category"": ""Clothing""...","[{""Timestamp"": ""2022-03-10T14:30:00Z""}, {""Time...","Great pair of jeans, very comfortable. Rating:...",32.50
1,1001,28,Female,City D,52000,"[{""Product Category"": ""Clothing"", ""Purchase Da...","[{""Product Category"": ""Home & Garden"", ""Timest...",Great customer service!,123.45
2,1001,28,Female,City D,65000,"[{""Product Category"": ""Electronics"", ""Purchase...","[{""Product Category"": ""Clothing"", ""Timestamp"":...",Great electronics. The sound quality is excell...,125.60
3,1001,45,Female,City D,70000,"{'Purchase Date': '2022-08-15', 'Product Categ...",{'Timestamp': '2022-09-03 14:30:00'},"{""Product 1"": {""Rating"": 4, ""Review"": ""Great e...",327.60
4,1002,34,Male,City E,45000,"{'Purchase Date': '2022-07-25', 'Product Categ...",{'Timestamp': '2022-08-10 17:15:00'},"{""Product 1"": {""Rating"": 3, ""Review"": ""Good pr...",214.90

In [3]:
df = df.set_index('Customer ID')
df.head()

,Age,Gender,Location,Annual Income,Purchase History,Browsing History,Product Reviews,Time on Site
Customer ID,,,,,,,,
1001,25,Female,City D,45000,"[{""Date"": ""2022-03-05"", ""Category"": ""Clothing""...","[{""Timestamp"": ""2022-03-10T14:30:00Z""}, {""Time...","Great pair of jeans, very comfortable. Rating:...",32.50
1001,28,Female,City D,52000,"[{""Product Category"": ""Clothing"", ""Purchase Da...","[{""Product Category"": ""Home & Garden"", ""Timest...",Great customer service!,123.45
1001,28,Female,City D,65000,"[{""Product Category"": ""Electronics"", ""Purchase...","[{""Product Category"": ""Clothing"", ""Timestamp"":...",Great electronics. The sound quality is excell...,125.60
1001,45,Female,City D,70000,"{'Purchase Date': '2022-08-15', 'Product Categ...",{'Timestamp': '2022-09-03 14:30:00'},"{""Product 1"": {""Rating"": 4, ""Review"": ""Great e...",327.60
1002,34,Male,City E,45000,"{'Purchase Date': '2022-07-25', 'Product Categ...",{'Timestamp': '2022-08-10 17:15:00'},"{""Product 1"": {""Rating"": 3, ""Review"": ""Good pr...",214.90

In [23]:
df["Purchase History"].loc[1004]

Customer ID
1004    {'Purchase Date': '2022-07-20', 'Product Categ...
1004    {'Purchase Date': '2022-04-25', 'Product Categ...
1004    {'Purchase Date': '2022-05-08', 'Product Categ...
1004    [{"Product Category": "Clothing", "Purchase Da...
Name: Purchase History, dtype: object

In [13]:
df.shape

(50, 8)

In [19]:
# data = [df["Purchase History"]]
# data

In [20]:
import pandas as pd

data = [df]

events = []

for user in data:
    user_id = user["Customer ID"]
    
    # просмотры
    for view in user.get("Browsing History	", []):
        events.append({
            "Customer ID": user_id,
            "event_type": "view",
            "product_id": view["product_id"],
            "timestamp": view["timestamp"]
        })
    
    # покупки
    for purchase in user.get("Purchase History", []):
        events.append({
            "Customer ID": user_id,
            "event_type": "purchase",
            "product_id": purchase["product_id"],
            "Date": purchase["timestamp"]
        })

df = pd.DataFrame(events)

KeyError: 'Customer ID'

In [35]:
data[0].keys()

Index(['Age', 'Gender', 'Location', 'Annual Income', 'Purchase History',
       'Browsing History', 'Product Reviews', 'Time on Site'],
      dtype='object')

In [49]:
import ast

keys = set()

for _, item in df.iterrows():
    purchases = item["Purchase History"]
    
    if isinstance(purchases, str):
        purchases = ast.literal_eval(purchases)
    
    if isinstance(purchases, list):
        for p in purchases:
            if isinstance(p, dict):
                keys.update(p.keys())

print(keys)

{'Price', 'Purchase Date', 'Category', 'Product Category', 'Date'}

In [52]:
import ast

keys_2 = set()

for _, item in df.iterrows():
    Browsing = item["Browsing History"]
    
    if isinstance(Browsing, str):
        Browsing = ast.literal_eval(Browsing)
    
    if isinstance(Browsing, list):
        for b in Browsing:
            if isinstance(b, dict):
                keys_2.update(b.keys())

print(keys_2)

{'Timestamp', 'Product Category'}

In [39]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [50]:
for _, item in df.iterrows():
    purchases = item["Purchase History"]
    
    print(type(purchases))
    print(purchases)
    break

<class 'str'>
[{"Date": "2022-03-05", "Category": "Clothing", "Price": 34.99}, {"Date": "2022-02-12", "Category": "Electronics", "Price": 129.99}, {"Date": "2022-01-20", "Category": "Home & Garden", "Price": 29.99}]

In [51]:
df

,Age,Gender,Location,Annual Income,Purchase History,Browsing History,Product Reviews,Time on Site
Customer ID,,,,,,,,
1001,25,Female,City D,45000,"[{""Date"": ""2022-03-05"", ""Category"": ""Clothing""...","[{""Timestamp"": ""2022-03-10T14:30:00Z""}, {""Time...","Great pair of jeans, very comfortable. Rating:...",32.50
1001,28,Female,City D,52000,"[{""Product Category"": ""Clothing"", ""Purchase Da...","[{""Product Category"": ""Home & Garden"", ""Timest...",Great customer service!,123.45
1001,28,Female,City D,65000,"[{""Product Category"": ""Electronics"", ""Purchase...","[{""Product Category"": ""Clothing"", ""Timestamp"":...",Great electronics. The sound quality is excell...,125.60
1001,45,Female,City D,70000,"{'Purchase Date': '2022-08-15', 'Product Categ...",{'Timestamp': '2022-09-03 14:30:00'},"{""Product 1"": {""Rating"": 4, ""Review"": ""Great e...",327.60
1002,34,Male,City E,45000,"{'Purchase Date': '2022-07-25', 'Product Categ...",{'Timestamp': '2022-08-10 17:15:00'},"{""Product 1"": {""Rating"": 3, ""Review"": ""Good pr...",214.90
1003,56,Other,City F,90000,"{'Purchase Date': '2022-09-01', 'Product Categ...",{'Timestamp': '2022-06-25 10:45:00'},"{""Product 1"": {""Rating"": 5, ""Review"": ""Awesome...",486.30
1004,29,Female,City G,60000,"{'Purchase Date': '2022-07-20', 'Product Categ...",{'Timestamp': '2022-08-15 13:20:00'},"{""Product 1"": {""Rating"": 4, ""Review"": ""Great p...",378.50
1005,42,Male,City H,75000,"{'Purchase Date': '2022-08-28', 'Product Categ...",{'Timestamp': '2022-09-12 16:35:00'},"{""Product 1"": {""Rating"": 3, ""Review"": ""Good pr...",289.80
1006,51,Other,City I,85000,"{'Purchase Date': '2022-09-05', 'Product Categ...",{'Timestamp': '2022-06-28 09:00:00'},"{""Product 1"": {""Rating"": 5, ""Review"": ""Outstan...",456.20
1007,36,Female,City J,55000,"{'Purchase Date': '2022-07-27', 'Product Categ...",{'Timestamp': '2022-08-17 14:50:00'},"{""Product 1"": {""Rating"": 4, ""Review"": ""Good pr...",334.90
1008,48,Male,City K,80000,"{'Purchase Date': '2022-09-08', 'Product Categ...",{'Timestamp': '2022-06-30 11:15:00'},"{""Product 1"": {""Rating"": 3, ""Review"": ""Good pr...",298.60
1009,25,Other,City L,40000,"{'Purchase Date': '2022-08-25', 'Product Categ...",{'Timestamp': '2022-09-14 10:00:00'},"{""Product 1"": {""Rating"": 4, ""Review"": ""Great p...",312.50
1001,45,Female,City D,75000,"{'Purchase Date': '2022-03-05', 'Product Categ...",{'Timestamp': '2022-03-06 14:30:00'},"{""Review Text"": ""Great quality clothes!"", ""Rat...",120.00
1002,32,Male,City A,50000,"{'Purchase Date': '2022-02-15', 'Product Categ...",{'Timestamp': '2022-05-12 16:15:00'},"{""Review Text"": ""Good product, but could be ch...",75.00
1003,60,Other,City B,80000,"{'Purchase Date': '2022-01-18', 'Product Categ...",{'Timestamp': '2022-06-03 10:45:00'},"{""Review Text"": ""Very satisfied with my purcha...",200.00
1004,28,Female,City C,45000,"{'Purchase Date': '2022-04-25', 'Product Categ...",{'Timestamp': '2022-07-08 13:00:00'},"{""Review Text"": ""Not what I expected."", ""Ratin...",150.00
1005,55,Male,City E,90000,"{'Purchase Date': '2022-05-20', 'Product Categ...",{'Timestamp': '2022-08-04 09:30:00'},"{""Review Text"": ""Excellent product, highly rec...",300.00
1006,38,Female,City F,65000,"{'Purchase Date': '2022-06-15', 'Product Categ...",{'Timestamp': '2022-09-02 11:15:00'},"{""Review Text"": ""Awesome purchase!"", ""Rating"": 5}",250.00
1007,42,Male,City G,70000,"{'Purchase Date': '2022-07-22', 'Product Categ...",{'Timestamp': '2022-10-07 14:45:00'},"{""Review Text"": ""Good product, but not worth t...",180.00
1008,50,Female,City H,85000,"{'Purchase Date': '2022-08-08', 'Product Categ...",{'Timestamp': '2022-11-02 10:30:00'},"{""Review Text"": ""Great product, highly recomme...",280.00
1009,35,Male,City I,55000,"{'Purchase Date': '2022-09-20', 'Product Categ...",{'Timestamp': '2022-12-06 12:00:00'},"{""Review Text"": ""Satisfied with my purchase!"",...",220.00
1010,48,Female,City J,75000,"{'Purchase Date': '2022-10-15', 'Product Categ...",{'Timestamp': '2022-12-21 15:30:00'},"{""Review Text"": ""Excellent product, highly rec...",200.00
1011,30,Male,City K,40000,"{'Purchase Date': '2022-11-05', 'Product Categ...",{'Timestamp': '2023-01-11 08:45:00'},"{""Review Text"": ""Good product, but could be be...",160.00
1012,65,Female,City L,95000,"{'Purchase Date': '2022-12-25', 'Product Categ...",{'Timestamp': '2023-02-06 13:15:00'},"{""Review Text"": ""Excellent product, highly rec...",240.00
1001,24,Female,City D,45000,"[{""Purchase Date"": ""2022-09-15"", ""Product Cate...","[{""Timestamp"": ""2022-08-20T14:30:00Z""}, {""Time...",This dress is amazing! I love the color and fi...,120.50
1001,35,Female,City D,50000,"{'Purchase Date': '2022-05-15', 'Product Categ...",{'Timestamp': '2022-04-20T14:30:00Z'},The blouse is so comfortable and stylish. 5 st...,120.00
1002,45,Male,City E,80000,"{'Purchase Date': '2022-06-12', 'Product Categ...",{'Timestamp': '2022-05-25T17:45:00Z'},The headphones are great. Sound quality is exc...,300.00
1003,28,Female,City F,60000,"{'Purchase Date': '2022-05-28', 'Product Categ...",{'Timestamp': '2022-06-01T09:15:00Z'},The dress fits perfectly. I love it. 5 stars!,250.00
1004,52,Male,City G,70000,"{'Purchase Date': '2022-05-08', 'Product Categ...",{'Timestamp': '2022-05-22T10:30:00Z'},The vacuum cleaner works great. 4 stars.,350.00
1005,31,Female,City H,45000,"{'Purchase Date': '2022-05-18', 'Product Categ...",{'Timestamp': '2022-05-30T13:45:00Z'},"The top is nice, but the size is a bit small. ...",200.00
1006,48,Male,City I,90000,"{'Purchase Date': '2022-05-23', 'Product Categ...",{'Timestamp': '2022-06-06T08:00:00Z'},The phone is fantastic. 5 stars!,400.00
1007,60,Female,City J,65000,"{'Purchase Date': '2022-05-25', 'Product Categ...",{'Timestamp': '2022-06-15T11:30:00Z'},The shirt is comfortable. 4 stars.,300.00
1008,55,Male,City K,85000,"{'Purchase Date': '2022-05-20', 'Product Categ...",{'Timestamp': '2022-05-28T15:15:00Z'},The laptop is excellent. 5 stars!,450.00
1009,29,Female,City L,40000,"{'Purchase Date': '2022-05-16', 'Product Categ...",{'Timestamp': '2022-05-31T16:45:00Z'},The shoes are comfortable. 4.5 stars.,250.00
1010,58,Male,City M,75000,"{'Purchase Date': '2022-05-12', 'Product Categ...",{'Timestamp': '2022-05-29T10:30:00Z'},The coffee maker is great. 5 stars!,350.00
1011,36,Female,City N,55000,"{'Purchase Date': '2022-05-27', 'Product Categ...",{'Timestamp': '2022-06-13T13:00:00Z'},The skirt is lovely. 4.5 stars.,200.00
1012,42,Male,City O,95000,"{'Purchase Date': '2022-05-22', 'Product Categ...",{'Timestamp': '2022-05-26T11:15:00Z'},The TV is amazing. 5 stars!,300.00
1013,50,Female,City P,68000,"{'Purchase Date': '2022-05-19', 'Product Categ...",{'Timestamp': '2022-06-08T14:30:00Z'},The bedding is comfortable. 4 stars.,250.00
1001,32,Female,City D,65000,"[{""Product Category"": ""Clothing"", ""Purchase Da...","[{""Product Category"": ""Home & Garden"", ""Timest...",Great find! 5 stars,72.30
1001,35,Female,City D,60000,"[{""Product Category"": ""Electronics"", ""Purchase...","[{""Product Category"": ""Home & Garden"", ""Timest...","Great product, very happy with my purchase.",123.60
1002,42,Male,City E,75000,"[{""Product Category"": ""Clothing"", ""Purchase Da...","[{""Product Category"": ""Electronics"", ""Timestam...",The product arrived quickly and in great condi...,246.90
1001,32,Female,City D,55000,"[{""Product Category"": ""Electronics"", ""Purchase...","[{""Product Category"": ""Home & Garden"", ""Timest...","Great headphones, sound quality is amazing.",75.20
1001,28,Female,City D,65000,"[{""Product Category"": ""Clothing"", ""Purchase Da...","[{""Product Category"": ""Home & Garden"", ""Timest...",Great purchase! The shoes are so comfortable a...,120.50
1002,42,Male,City E,80000,"[{""Product Category"": ""Electronics"", ""Purchase...","[{""Product Category"": ""Clothing"", ""Timestamp"":...",I'm really happy with my new phone. The batter...,250.00
1003,35,Other,City F,50000,"[{""Product Category"": ""Clothing"", ""Purchase Da...","[{""Product Category"": ""Home & Garden"", ""Timest...",The headphones are amazing! The sound quality ...,75.00
1004,52,Female,City G,100000,"[{""Product Category"": ""Clothing"", ""Purchase Da...","[{""Product Category"": ""Electronics"", ""Timestam...",I love my new kitchen gadget! It's so efficien...,300.00
1005,24,Male,City H,45000,"[{""Product Category"": ""Electronics"", ""Purchase...","[{""Product Category"": ""Clothing"", ""Timestamp"":...",The laptop is perfect for my needs. It's light...,100.00
1001,34,Female,City D,55000,"[{""Purchase Date"": ""2022-07-02"",""Product Categ...","[{""Timestamp"": ""2022-08-14T09:30:00Z""},{""Times...",The clothing arrived quickly and fits great! 5...,120.00
1002,45,Male,City E,87000,"[{""Purchase Date"": ""2022-07-08"",""Product Categ...","[{""Timestamp"": ""2022-08-12T16:00:00Z""},{""Times...",The electronics were excellent quality and arr...,350.00
1003,29,Other,City F,42000,"[{""Purchase Date"": ""2022-07-01"",""Product Categ...","[{""Timestamp"": ""2022-08-13T13:45:00Z""},{""Times...",The electronics were as described and arrived ...,200.00

In [57]:
def parse_purchases(purchases):
    """
    Преобразует поле Purchase History / Browsing History в список словарей
    """
    if isinstance(purchases, str):
        try:
            # ast.literal_eval безопасно превращает строку в Python-объект
            return ast.literal_eval(purchases)
        except:
            return []  # если не получилось, возвращаем пустой список
    elif isinstance(purchases, list):
        return purchases
    else:
        return []  # если тип неожиданный

In [60]:
events = []
for _, item in df.iterrows():
    user_id = item.name
    purchases = parse_purchases(item["Purchase History"])
    Browsing = parse_purchases(item["Browsing History"])
    if isinstance(purchases, list):
        for p in purchases:
            if isinstance(p, dict):
                category = None
                for k in p:
                    if "Category" in k:
                        category = p[k]
                        break
                Date = None
                for k in p:
                    if "Date" in k:
                        catagory = p[k]
                        break
                events.append({
                    "user_id": user_id,
                    "category": category,
                    "timestamp": Date,
                    "event_type": "purchase",
                    "Price": p.get("Price")
                })
    if isinstance(Browsing, list):
        for b in Browsing:
            if isinstance(b, dict):
                events.append({
                    "user_id": user_id,
                    "category": b.get('Product Category'),
                    "timestamp": b.get('Timestamp'),
                    "event_type": "view",
                    "Price": None
                })
                
            
    
    

df_events = pd.DataFrame(events)

In [61]:
df_events

    user_id       category             timestamp event_type   Price
0      1001       Clothing                  None   purchase   34.99
1      1001    Electronics                  None   purchase  129.99
2      1001  Home & Garden                  None   purchase   29.99
3      1001           None  2022-03-10T14:30:00Z       view     NaN
4      1001           None  2022-03-11T09:45:00Z       view     NaN
..      ...            ...                   ...        ...     ...
65     1003       Clothing                  None   purchase   50.00
66     1003  Home & Garden                  None   purchase   30.00
67     1003           None  2022-08-13T13:45:00Z       view     NaN
68     1003           None  2022-07-26T07:00:00Z       view     NaN
69     1003           None  2022-06-02T15:30:00Z       view     NaN

[70 rows x 5 columns]

In [62]:

df_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     70 non-null     int64
 1   category    55 non-null     object
 2   timestamp   36 non-null     object
 3   event_type  70 non-null     object
 4   Price       34 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 2.9+ KB

In [63]:
df_events.describe()

           user_id       Price
count    70.000000   34.000000
mean   1001.885714  152.325588
std       1.198343  121.870153
min    1001.000000   25.600000
25%    1001.000000   45.420000
50%    1001.000000  129.990000
75%    1002.750000  237.492500
max    1005.000000  450.000000

In [65]:
df_events[df_events["event_type"] == "purchase"]

    user_id       category timestamp event_type   Price
0      1001       Clothing      None   purchase   34.99
1      1001    Electronics      None   purchase  129.99
2      1001  Home & Garden      None   purchase   29.99
6      1001       Clothing      None   purchase   34.56
7      1001    Electronics      None   purchase  150.99
10     1001    Electronics      None   purchase  345.50
11     1001  Home & Garden      None   purchase  279.99
14     1001       Clothing      None   purchase   34.50
18     1001       Clothing      None   purchase   45.23
19     1001    Electronics      None   purchase  250.34
22     1001    Electronics      None   purchase  250.50
23     1001       Clothing      None   purchase  125.80
26     1002       Clothing      None   purchase  150.20
27     1002  Home & Garden      None   purchase  450.00
30     1001    Electronics      None   purchase  249.99
32     1001       Clothing      None   purchase   45.99
33     1001    Electronics      None   purchase  199.99
36     1002    Electronics      None   purchase  249.99
37     1002  Home & Garden      None   purchase  129.99
40     1003       Clothing      None   purchase   34.99
41     1003    Electronics      None   purchase  149.99
44     1004       Clothing      None   purchase   79.99
45     1004  Home & Garden      None   purchase  399.99
48     1005    Electronics      None   purchase  129.99
49     1005  Home & Garden      None   purchase   59.99
52     1001       Clothing      None   purchase   25.60
53     1001    Electronics      None   purchase  120.00
54     1001  Home & Garden      None   purchase   35.00
58     1002    Electronics      None   purchase  420.00
59     1002       Clothing      None   purchase   75.00
60     1002  Home & Garden      None   purchase  200.00
64     1003    Electronics      None   purchase  180.00
65     1003       Clothing      None   purchase   50.00
66     1003  Home & Garden      None   purchase   30.00